using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Cell : MonoBehaviour
{
    public int xPos;
    public int yPos;
    public Unit standingUnit;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnMouseDown()
    {
        //Debug.Log("点击了单元格。");
        //Debug.Log("位置： " + transform.position.x + "," + transform.position.y);
        Debug.Log("位置： " + (xPos+1) + "," + (yPos+1));
    }
}
